spring:
  application:
    name: apigateway_service
  cloud:
    gateway:
      routes:
        - id: author_service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/author/**
        - id: user_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/user/**
        - id: authentication_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**
        - id: favorite_service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/fav/**

      discovery:
        locator:
          enabled: true


server:
  port: 8090